dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- name: memstat-collector
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: testmicro
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
